project: asm2go

backends:
    lxd:
        systems: [ubuntu-18.04]

suites:
    testdata/:
        summary: Keccak function on ARM/ARM64 example
        environment:
            GOARCH/arm: arm
            GOARM/arm: 7
            QEMU_EXEC/arm: qemu-arm-static
        kill-timeout: 30m
        prepare: |
            apt update
            apt install build-essential gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu qemu-user-static libvirt-bin wget -y -qq
            snap install go --classic --channel=1.10/stable
            export GOARCH=amd64
            export GOPATH=$(go env GOPATH)
            export PATH="$GOPATH/bin:$PATH"
            go get -u github.com/kardianos/govendor
            govendor sync
            govendor fetch +out
            go install ../../... 
        restore: | 
            snap remove go

path: /root/go/src/github.com/anonymouse64/asm2go