language: go
sudo: false
go:
  - 1.10.x
  - tip

go_import_path: github.com/anonymouse64/asm2go

addons:
  apt:
    packages:
      - gcc-arm-linux-gnueabihf
    update: true

install:
  - go get -u github.com/kardianos/govendor
  - govendor sync
  - govendor fetch +out

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
