language: go
sudo: false
go:
  - 1.10.x
  - tip

go_import_path: github.com/anonymouse64/asm2go

install:
  - go get -t -v ./cmd/...
  - go get -t -v ./assembler/...

script:
  - go test -v ./cmd/... ./assembler/...

addons:
  apt:
    packages:
      - gcc-arm-linux-gnueabihf
    update: true

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
