name: asm2go
version: '0.1'
summary: Translate native assembly functions into Plan9 syntax
description: |
  asm2go translates native assembly functions into a Plan9 syntax format usable with Go, without needing Cgo style linking requirements.
  Included in the amd64 snap are cross-compilers for ARM and ARM64 so no cross-compilers have to be installed into the host system.
  The ARM and ARM64 snap only have native compilers available to them.

grade: stable
confinement: strict

apps:
  asm2go:
    command: bin/asm2go

parts:
  go:
    source-tag: go1.10.2
    source-depth: 1
  asm2go:
    go-importpath: github.com/anonymouse64/asm2go
    after: [go]
    plugin: go
    source: .
    stage-packages:
      - on amd64: [gcc-arm-linux-gnueabihf, gcc-aarch64-linux-gnu]
      - build-essential
    override-build: |
      export GOPATH=$(dirname $PWD)/go
      go get -u github.com/kardianos/govendor
      export PATH="$GOPATH/bin:$PATH"
      cd $GOPATH/src/github.com/anonymouse64/asm2go
      govendor sync
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      go build -o $SNAPCRAFT_PART_INSTALL/bin/asm2go ./cmd/asm2go/asm2go.go
